name: Docker
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: docker build -t image .
    - name: Publish
      run: |
        docker tag image docker.pkg.github.com/jchv/ytdl-pvr/ytdl-pvr:${GITHUB_SHA}
        docker push docker.pkg.github.com/jchv/ytdl-pvr/ytdl-pvr:${GITHUB_SHA}
        docker tag image docker.pkg.github.com/jchv/ytdl-pvr/ytdl-pvr:latest
        docker push docker.pkg.github.com/jchv/ytdl-pvr/ytdl-pvr:latest
